apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: vitessbackups.planetscale.com
spec:
  group: planetscale.com
  names:
    kind: VitessBackup
    listKind: VitessBackupList
    plural: vitessbackups
    shortNames:
    - vtb
    singular: vitessbackup
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          type: object
        status:
          properties:
            complete:
              description: Complete indicates whether the backup ever completed.
              type: boolean
            engine:
              description: Engine is the Vitess backup engine implementation that
                was used.
              type: string
            finishedTime:
              description: FinishedTime is the time when the backup finished.
              format: date-time
              type: string
            position:
              description: Position is the replication position of the snapshot that
                was backed up. The position is expressed in the native, GTID-based
                format of the MySQL flavor that took the backup. This is only available
                after the backup is complete.
              type: string
            startTime:
              description: StartTime is the time when the backup started.
              format: date-time
              type: string
            storageDirectory:
              description: StorageDirectory is the name of the parent directory in
                storage that contains this backup.
              type: string
            storageName:
              description: StorageName is the name of the backup in storage. This
                is different from the name of the VitessBackup object created to represent
                metadata about the actual backup in storage.
              type: string
          type: object
  version: v2
  versions:
  - name: v2
    served: true
    storage: true
